// <auto-generated />
using System;
using IdentityCRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityCRUD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230512065502_AddProduct")]
    partial class AddProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdentityCRUD.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IdentityCRUD.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Test",
                            Name = "Coffee 1",
                            Price = 86L,
                            QuantityInStock = 13,
                            Type = "Capu"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Test",
                            Name = "Coffee 2",
                            Price = 92L,
                            QuantityInStock = 10,
                            Type = "Esresso"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Test",
                            Name = "Coffee 3",
                            Price = 66L,
                            QuantityInStock = 2,
                            Type = "Drip"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Test",
                            Name = "Coffee 4",
                            Price = 24L,
                            QuantityInStock = 88,
                            Type = "Drip"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Test",
                            Name = "Coffee 5",
                            Price = 47L,
                            QuantityInStock = 58,
                            Type = "Drip"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Test",
                            Name = "Coffee 6",
                            Price = 16L,
                            QuantityInStock = 44,
                            Type = "Drip"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Test",
                            Name = "Coffee 7",
                            Price = 74L,
                            QuantityInStock = 63,
                            Type = "Red"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Test",
                            Name = "Coffee 8",
                            Price = 27L,
                            QuantityInStock = 18,
                            Type = "Capu"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Test",
                            Name = "Coffee 9",
                            Price = 10L,
                            QuantityInStock = 42,
                            Type = "Esresso"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Test",
                            Name = "Coffee 10",
                            Price = 62L,
                            QuantityInStock = 23,
                            Type = "Capu"
                        });
                });

            modelBuilder.Entity("IdentityCRUD.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://picsum.photos/id/1/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://picsum.photos/id/2/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://picsum.photos/id/3/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://picsum.photos/id/4/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://picsum.photos/id/5/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://picsum.photos/id/6/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://picsum.photos/id/7/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://picsum.photos/id/8/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://picsum.photos/id/9/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://picsum.photos/id/10/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://picsum.photos/id/11/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://picsum.photos/id/12/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://picsum.photos/id/13/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://picsum.photos/id/14/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://picsum.photos/id/15/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://picsum.photos/id/16/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://picsum.photos/id/17/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://picsum.photos/id/18/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://picsum.photos/id/19/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://picsum.photos/id/20/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://picsum.photos/id/21/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://picsum.photos/id/22/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 23,
                            Image = "https://picsum.photos/id/23/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 24,
                            Image = "https://picsum.photos/id/24/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 25,
                            Image = "https://picsum.photos/id/25/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 26,
                            Image = "https://picsum.photos/id/26/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            Image = "https://picsum.photos/id/27/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 28,
                            Image = "https://picsum.photos/id/28/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 29,
                            Image = "https://picsum.photos/id/29/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 30,
                            Image = "https://picsum.photos/id/30/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 31,
                            Image = "https://picsum.photos/id/31/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 32,
                            Image = "https://picsum.photos/id/32/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 33,
                            Image = "https://picsum.photos/id/33/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 34,
                            Image = "https://picsum.photos/id/34/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 35,
                            Image = "https://picsum.photos/id/35/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 36,
                            Image = "https://picsum.photos/id/36/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 37,
                            Image = "https://picsum.photos/id/37/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 38,
                            Image = "https://picsum.photos/id/38/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 39,
                            Image = "https://picsum.photos/id/39/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 40,
                            Image = "https://picsum.photos/id/40/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 41,
                            Image = "https://picsum.photos/id/41/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 42,
                            Image = "https://picsum.photos/id/42/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 43,
                            Image = "https://picsum.photos/id/43/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 44,
                            Image = "https://picsum.photos/id/44/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 45,
                            Image = "https://picsum.photos/id/45/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 46,
                            Image = "https://picsum.photos/id/46/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 47,
                            Image = "https://picsum.photos/id/47/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 48,
                            Image = "https://picsum.photos/id/48/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 49,
                            Image = "https://picsum.photos/id/49/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 50,
                            Image = "https://picsum.photos/id/50/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 51,
                            Image = "https://picsum.photos/id/51/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 52,
                            Image = "https://picsum.photos/id/52/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 53,
                            Image = "https://picsum.photos/id/53/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 54,
                            Image = "https://picsum.photos/id/54/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 55,
                            Image = "https://picsum.photos/id/55/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 56,
                            Image = "https://picsum.photos/id/56/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 57,
                            Image = "https://picsum.photos/id/57/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 58,
                            Image = "https://picsum.photos/id/58/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 59,
                            Image = "https://picsum.photos/id/59/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 60,
                            Image = "https://picsum.photos/id/60/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 61,
                            Image = "https://picsum.photos/id/61/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 62,
                            Image = "https://picsum.photos/id/62/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 63,
                            Image = "https://picsum.photos/id/63/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 64,
                            Image = "https://picsum.photos/id/64/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 65,
                            Image = "https://picsum.photos/id/65/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 66,
                            Image = "https://picsum.photos/id/66/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 67,
                            Image = "https://picsum.photos/id/67/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 68,
                            Image = "https://picsum.photos/id/68/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 69,
                            Image = "https://picsum.photos/id/69/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 70,
                            Image = "https://picsum.photos/id/70/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 71,
                            Image = "https://picsum.photos/id/71/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 72,
                            Image = "https://picsum.photos/id/72/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 73,
                            Image = "https://picsum.photos/id/73/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 74,
                            Image = "https://picsum.photos/id/74/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 75,
                            Image = "https://picsum.photos/id/75/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 76,
                            Image = "https://picsum.photos/id/76/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 77,
                            Image = "https://picsum.photos/id/77/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 78,
                            Image = "https://picsum.photos/id/78/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 79,
                            Image = "https://picsum.photos/id/79/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 80,
                            Image = "https://picsum.photos/id/80/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 81,
                            Image = "https://picsum.photos/id/81/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 82,
                            Image = "https://picsum.photos/id/82/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 83,
                            Image = "https://picsum.photos/id/83/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 84,
                            Image = "https://picsum.photos/id/84/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 85,
                            Image = "https://picsum.photos/id/85/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 86,
                            Image = "https://picsum.photos/id/86/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 87,
                            Image = "https://picsum.photos/id/87/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 88,
                            Image = "https://picsum.photos/id/88/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 89,
                            Image = "https://picsum.photos/id/89/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 90,
                            Image = "https://picsum.photos/id/90/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 91,
                            Image = "https://picsum.photos/id/91/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 92,
                            Image = "https://picsum.photos/id/92/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 93,
                            Image = "https://picsum.photos/id/93/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 94,
                            Image = "https://picsum.photos/id/94/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 95,
                            Image = "https://picsum.photos/id/95/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 96,
                            Image = "https://picsum.photos/id/96/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 97,
                            Image = "https://picsum.photos/id/97/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 98,
                            Image = "https://picsum.photos/id/98/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 99,
                            Image = "https://picsum.photos/id/99/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 100,
                            Image = "https://picsum.photos/id/100/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 101,
                            Image = "https://picsum.photos/id/101/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 102,
                            Image = "https://picsum.photos/id/102/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 103,
                            Image = "https://picsum.photos/id/103/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 104,
                            Image = "https://picsum.photos/id/104/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 105,
                            Image = "https://picsum.photos/id/105/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 106,
                            Image = "https://picsum.photos/id/106/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 107,
                            Image = "https://picsum.photos/id/107/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 108,
                            Image = "https://picsum.photos/id/108/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 109,
                            Image = "https://picsum.photos/id/109/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 110,
                            Image = "https://picsum.photos/id/110/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 111,
                            Image = "https://picsum.photos/id/111/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 112,
                            Image = "https://picsum.photos/id/112/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 113,
                            Image = "https://picsum.photos/id/113/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 114,
                            Image = "https://picsum.photos/id/114/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 115,
                            Image = "https://picsum.photos/id/115/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 116,
                            Image = "https://picsum.photos/id/116/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 117,
                            Image = "https://picsum.photos/id/117/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 118,
                            Image = "https://picsum.photos/id/118/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 119,
                            Image = "https://picsum.photos/id/119/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 120,
                            Image = "https://picsum.photos/id/120/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 121,
                            Image = "https://picsum.photos/id/121/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 122,
                            Image = "https://picsum.photos/id/122/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 123,
                            Image = "https://picsum.photos/id/123/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 124,
                            Image = "https://picsum.photos/id/124/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 125,
                            Image = "https://picsum.photos/id/125/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 126,
                            Image = "https://picsum.photos/id/126/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 127,
                            Image = "https://picsum.photos/id/127/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 128,
                            Image = "https://picsum.photos/id/128/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 129,
                            Image = "https://picsum.photos/id/129/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 130,
                            Image = "https://picsum.photos/id/130/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 131,
                            Image = "https://picsum.photos/id/131/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 132,
                            Image = "https://picsum.photos/id/132/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 133,
                            Image = "https://picsum.photos/id/133/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 134,
                            Image = "https://picsum.photos/id/134/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 135,
                            Image = "https://picsum.photos/id/135/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 136,
                            Image = "https://picsum.photos/id/136/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 137,
                            Image = "https://picsum.photos/id/137/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 138,
                            Image = "https://picsum.photos/id/138/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 139,
                            Image = "https://picsum.photos/id/139/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 140,
                            Image = "https://picsum.photos/id/140/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 141,
                            Image = "https://picsum.photos/id/141/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 142,
                            Image = "https://picsum.photos/id/142/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 143,
                            Image = "https://picsum.photos/id/143/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 144,
                            Image = "https://picsum.photos/id/144/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 145,
                            Image = "https://picsum.photos/id/145/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 146,
                            Image = "https://picsum.photos/id/146/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 147,
                            Image = "https://picsum.photos/id/147/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 148,
                            Image = "https://picsum.photos/id/148/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 149,
                            Image = "https://picsum.photos/id/149/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 150,
                            Image = "https://picsum.photos/id/150/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 151,
                            Image = "https://picsum.photos/id/151/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 152,
                            Image = "https://picsum.photos/id/152/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 153,
                            Image = "https://picsum.photos/id/153/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 154,
                            Image = "https://picsum.photos/id/154/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 155,
                            Image = "https://picsum.photos/id/155/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 156,
                            Image = "https://picsum.photos/id/156/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 157,
                            Image = "https://picsum.photos/id/157/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 158,
                            Image = "https://picsum.photos/id/158/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 159,
                            Image = "https://picsum.photos/id/159/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 160,
                            Image = "https://picsum.photos/id/160/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 161,
                            Image = "https://picsum.photos/id/161/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 162,
                            Image = "https://picsum.photos/id/162/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 163,
                            Image = "https://picsum.photos/id/163/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 164,
                            Image = "https://picsum.photos/id/164/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 165,
                            Image = "https://picsum.photos/id/165/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 166,
                            Image = "https://picsum.photos/id/166/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 167,
                            Image = "https://picsum.photos/id/167/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 168,
                            Image = "https://picsum.photos/id/168/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 169,
                            Image = "https://picsum.photos/id/169/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 170,
                            Image = "https://picsum.photos/id/170/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 171,
                            Image = "https://picsum.photos/id/171/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 172,
                            Image = "https://picsum.photos/id/172/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 173,
                            Image = "https://picsum.photos/id/173/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 174,
                            Image = "https://picsum.photos/id/174/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 175,
                            Image = "https://picsum.photos/id/175/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 176,
                            Image = "https://picsum.photos/id/176/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 177,
                            Image = "https://picsum.photos/id/177/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 178,
                            Image = "https://picsum.photos/id/178/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 179,
                            Image = "https://picsum.photos/id/179/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 180,
                            Image = "https://picsum.photos/id/180/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 181,
                            Image = "https://picsum.photos/id/181/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 182,
                            Image = "https://picsum.photos/id/182/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 183,
                            Image = "https://picsum.photos/id/183/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 184,
                            Image = "https://picsum.photos/id/184/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 185,
                            Image = "https://picsum.photos/id/185/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 186,
                            Image = "https://picsum.photos/id/186/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 187,
                            Image = "https://picsum.photos/id/187/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 188,
                            Image = "https://picsum.photos/id/188/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 189,
                            Image = "https://picsum.photos/id/189/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 190,
                            Image = "https://picsum.photos/id/190/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 191,
                            Image = "https://picsum.photos/id/191/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 192,
                            Image = "https://picsum.photos/id/192/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 193,
                            Image = "https://picsum.photos/id/193/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 194,
                            Image = "https://picsum.photos/id/194/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 195,
                            Image = "https://picsum.photos/id/195/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 196,
                            Image = "https://picsum.photos/id/196/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 197,
                            Image = "https://picsum.photos/id/197/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 198,
                            Image = "https://picsum.photos/id/198/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 199,
                            Image = "https://picsum.photos/id/199/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 200,
                            Image = "https://picsum.photos/id/200/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 201,
                            Image = "https://picsum.photos/id/201/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 202,
                            Image = "https://picsum.photos/id/202/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 203,
                            Image = "https://picsum.photos/id/203/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 204,
                            Image = "https://picsum.photos/id/204/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 205,
                            Image = "https://picsum.photos/id/205/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 206,
                            Image = "https://picsum.photos/id/206/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 207,
                            Image = "https://picsum.photos/id/207/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 208,
                            Image = "https://picsum.photos/id/208/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 209,
                            Image = "https://picsum.photos/id/209/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 210,
                            Image = "https://picsum.photos/id/210/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 211,
                            Image = "https://picsum.photos/id/211/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 212,
                            Image = "https://picsum.photos/id/212/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 213,
                            Image = "https://picsum.photos/id/213/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 214,
                            Image = "https://picsum.photos/id/214/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 215,
                            Image = "https://picsum.photos/id/215/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 216,
                            Image = "https://picsum.photos/id/216/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 217,
                            Image = "https://picsum.photos/id/217/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 218,
                            Image = "https://picsum.photos/id/218/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 219,
                            Image = "https://picsum.photos/id/219/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 220,
                            Image = "https://picsum.photos/id/220/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 221,
                            Image = "https://picsum.photos/id/221/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 222,
                            Image = "https://picsum.photos/id/222/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 223,
                            Image = "https://picsum.photos/id/223/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 224,
                            Image = "https://picsum.photos/id/224/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 225,
                            Image = "https://picsum.photos/id/225/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 226,
                            Image = "https://picsum.photos/id/226/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 227,
                            Image = "https://picsum.photos/id/227/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 228,
                            Image = "https://picsum.photos/id/228/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 229,
                            Image = "https://picsum.photos/id/229/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 230,
                            Image = "https://picsum.photos/id/230/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 231,
                            Image = "https://picsum.photos/id/231/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 232,
                            Image = "https://picsum.photos/id/232/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 233,
                            Image = "https://picsum.photos/id/233/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 234,
                            Image = "https://picsum.photos/id/234/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 235,
                            Image = "https://picsum.photos/id/235/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 236,
                            Image = "https://picsum.photos/id/236/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 237,
                            Image = "https://picsum.photos/id/237/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 238,
                            Image = "https://picsum.photos/id/238/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 239,
                            Image = "https://picsum.photos/id/239/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 240,
                            Image = "https://picsum.photos/id/240/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 241,
                            Image = "https://picsum.photos/id/241/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 242,
                            Image = "https://picsum.photos/id/242/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 243,
                            Image = "https://picsum.photos/id/243/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 244,
                            Image = "https://picsum.photos/id/244/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 245,
                            Image = "https://picsum.photos/id/245/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 246,
                            Image = "https://picsum.photos/id/246/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 247,
                            Image = "https://picsum.photos/id/247/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 248,
                            Image = "https://picsum.photos/id/248/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 249,
                            Image = "https://picsum.photos/id/249/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 250,
                            Image = "https://picsum.photos/id/250/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 251,
                            Image = "https://picsum.photos/id/251/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 252,
                            Image = "https://picsum.photos/id/252/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 253,
                            Image = "https://picsum.photos/id/253/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 254,
                            Image = "https://picsum.photos/id/254/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 255,
                            Image = "https://picsum.photos/id/255/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 256,
                            Image = "https://picsum.photos/id/256/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 257,
                            Image = "https://picsum.photos/id/257/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 258,
                            Image = "https://picsum.photos/id/258/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 259,
                            Image = "https://picsum.photos/id/259/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 260,
                            Image = "https://picsum.photos/id/260/200/300",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 261,
                            Image = "https://picsum.photos/id/261/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 262,
                            Image = "https://picsum.photos/id/262/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 263,
                            Image = "https://picsum.photos/id/263/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 264,
                            Image = "https://picsum.photos/id/264/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 265,
                            Image = "https://picsum.photos/id/265/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 266,
                            Image = "https://picsum.photos/id/266/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 267,
                            Image = "https://picsum.photos/id/267/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 268,
                            Image = "https://picsum.photos/id/268/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 269,
                            Image = "https://picsum.photos/id/269/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 270,
                            Image = "https://picsum.photos/id/270/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 271,
                            Image = "https://picsum.photos/id/271/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 272,
                            Image = "https://picsum.photos/id/272/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 273,
                            Image = "https://picsum.photos/id/273/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 274,
                            Image = "https://picsum.photos/id/274/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 275,
                            Image = "https://picsum.photos/id/275/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 276,
                            Image = "https://picsum.photos/id/276/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 277,
                            Image = "https://picsum.photos/id/277/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 278,
                            Image = "https://picsum.photos/id/278/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 279,
                            Image = "https://picsum.photos/id/279/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 280,
                            Image = "https://picsum.photos/id/280/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 281,
                            Image = "https://picsum.photos/id/281/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 282,
                            Image = "https://picsum.photos/id/282/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 283,
                            Image = "https://picsum.photos/id/283/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 284,
                            Image = "https://picsum.photos/id/284/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 285,
                            Image = "https://picsum.photos/id/285/200/300",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 286,
                            Image = "https://picsum.photos/id/286/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 287,
                            Image = "https://picsum.photos/id/287/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 288,
                            Image = "https://picsum.photos/id/288/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 289,
                            Image = "https://picsum.photos/id/289/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 290,
                            Image = "https://picsum.photos/id/290/200/300",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 291,
                            Image = "https://picsum.photos/id/291/200/300",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 292,
                            Image = "https://picsum.photos/id/292/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 293,
                            Image = "https://picsum.photos/id/293/200/300",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 294,
                            Image = "https://picsum.photos/id/294/200/300",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 295,
                            Image = "https://picsum.photos/id/295/200/300",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 296,
                            Image = "https://picsum.photos/id/296/200/300",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 297,
                            Image = "https://picsum.photos/id/297/200/300",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 298,
                            Image = "https://picsum.photos/id/298/200/300",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 299,
                            Image = "https://picsum.photos/id/299/200/300",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ec94b5c9-f6c6-4bdf-a426-a9cf400f3078",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        },
                        new
                        {
                            Id = "13a5cd2f-3b0c-4e0e-9c6e-b8a16c774dff",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IdentityCRUD.Models.ProductImage", b =>
                {
                    b.HasOne("IdentityCRUD.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IdentityCRUD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IdentityCRUD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityCRUD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IdentityCRUD.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdentityCRUD.Models.Product", b =>
                {
                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
